#!python

"""Infers site-specific character preferences.

Written by Jesse Bloom."""


import argparse
import dms_tools.parsearguments


def main():
    """Main body of script."""
    parser = dms_tools.parsearguments.InferPreferencesParser()


if __name__ == '__main__':
    main() # run the script
